### ISSUE TITLE
References Druntime in betterC mode

### ISSUE THREAD

**Issue by codic12** [tchaloupka/bc-string#1]
This code compiles fine with dub normally
```d
import core.stdc.stdio;
import bc.string.format;

struct S {
  int x;
};

char* nogcFormatZ(string fmt = "%s", ARGS...)(auto ref ARGS args) {
    import bc.string.string : StringZ;
    static StringZ str;
    str.clear();
    nogcFormatTo!fmt(str, args);
    return str.ptr;
}
extern(C) void main() {
  S s;
  s.x = 5;
  printf("%s", nogcFormatZ(s));
}
```
but if I add betterC to build options. I get large linker errors on both dmd and ldc.  dmd's: https://hastebin.com/bobiqetoja.cpp

I must be doing something trivial wrong, do I have to eg specify a dub option?

**Comment by tchaloupka** [comment]
Well, a pretty dumb mistake on my side :)
Just left a `executable` as a `targetType` in `dub.sdl` betterC subconfiguration..

I've tested your code with this:
```SDL
dependency "bc-string" version="~>1.2.0"
subConfiguration "bc-string" "betterC"
buildOptions "betterC"
```

And it worked with the fix.
I'll release fixed version.

**Comment by codic12** [comment]
Thanks!

**Comment by codic12** [comment]
(also, I can't make it work with that dub.sdl, I need to use ~master instead of ~>1.2.0 or it says invalid version.)

**Comment by tchaloupka** [comment]
I've checked the code.dlang.org and package hasn't been updated automatically after release (that should have been fixed recently). Trigered it automatically and it's ok now.
